config/routes.rb
TMS::Application.routes.draw do
  get "personalization/index"

  resources :task_logs

  get "sample_front/index"

  get "front_samples/index"

  get "task_front/top3Serial"

  get "task_front/top3All"

  get "task_front/taskonetwo"
  
  get "users/roster"

  resources :samples

  resources :manids

  resources :test_times

  get "sas_front/index"

  get "sas_front/reports"

  get "sas_front/deleteSa"

  resources :sas

  resources :targets

  resources :setups

  get "sas/index"

  resources :test_progs

  get "import_resource/import"

  get "import/npi"

  get "cost/import"

  resources :costings

  resources :projects

  resources :can_subs

  resources :can_mains

  resources :resources

  
  get "resource/index"
  
  get "resource/key_projects"

  get "admin/login"

  get "admin/logout"

  get "admin/index"

  get "main/test"

  resources :tasks

  resources :devices

  resources :users

  get "main/index"

  resources :ptos
  
  resources :sas_front do
    member do
      get 'mail'
    end
  end

  resources :tasks do
    member do
      get 'duplicate'
    end
  end

  match ':controller(/:action(/:id(.:format)))'
  
  resources :priority do
    collection do
      post 'reorder'
    end
  end
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  has_one :manid
  
  def self.linked_tables
    t=self.order(manids.device).joins('INNER JOIN manids ON manids.id = samples.manid_id')
    
    
    #t = self.where("tasks.complete = 'f' AND tasks.assignee_id IS NOT NULL AND category < '5'").order("users.fullname, tasks.priority").joins('INNER JOIN users ON users.id = tasks.assignee_id').select('users.fullname, tasks.*').includes("requester").includes("assignee")
    
    
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  # GET /samples
  # GET /samples.xml
  def index
    @samples = Sample.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @samples }
    end
  end

  # GET /samples/1
  # GET /samples/1.xml
  def show
    @sample = Sample.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sample }
    end
  end

  # GET /samples/new
  # GET /samples/new.xml
  def new
    @sample = Sample.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sample }
    end
  end

  # GET /samples/1/edit
  def edit
    @sample = Sample.find(params[:id])
  end

  # POST /samples
  # POST /samples.xml
  def create
    @sample = Sample.new(params[:sample])

    respond_to do |format|
      if @sample.save
        format.html { redirect_to(@sample, :notice => 'Sample was successfully created.') }
        format.xml  { render :xml => @sample, :status => :created, :location => @sample }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sample.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /samples/1
  # PUT /samples/1.xml
  def update
    @sample = Sample.find(params[:id])

    respond_to do |format|
      if @sample.update_attributes(params[:sample])
        format.html { redirect_to(@sample, :notice => 'Sample was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sample.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.xml
  def destroy
    @sample = Sample.find(params[:id])
    @sample.destroy

    respond_to do |format|
      format.html { redirect_to(samples_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.erb
<%= form_for(@sample) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b>MANID Record Number</b><br />
    <%= f.text_field :manid_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :dateExchange, 'Secret/Signature Exchange Date' %><br />
    <%= f.text_field :dateExchange %>
  </div>
  <div class="field">
    <%= f.label :dateSamples, 'Samples Shipped Date' %><br />
    <%= f.text_field :dateSamples %>
  </div>
  <div class="field">
    <%= f.label :dateCustApproval, 'Customer Approval Date' %><br />
    <%= f.text_field :dateCustApproval %>

  <div class="field">
    <%= f.label :dateReleaseProduction, 'Production Program Available Date' %><br />
    <%= f.text_field :dateReleaseProduction %>
  </div>

  <div class="field">
    <%= f.label :target, 'Target Production Program Available Date' %><br />
    <%= f.text_field :target %>
  </div>

  </div>
  <div class="field">
    <%= f.label :dateQAEnable, 'Production Program Released Date' %><br />
    <%= f.text_field :dateQAEnable %>
  </div>
  <div class="field">
    <%= f.label :crs, 'CRS' %><br />
    <%= f.text_field :crs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<h1>Customer Qualification Tracker</h1>

<table cellspacing='10' class='display' id='prr' width='100%'>
	<thead>
		  <tr>
    <th>Customer</th>
    <th>CAN</th>
    <th>Status</th>
    <th>Sec/Sig Exchange</th>
    <th>Samples Sent</th>
    <th>Customer Approval</th>
    <th>FT Production Available</th>
    <th>FT Production Available Target</th>
    <th>Production Release</th>
    <th>CRS</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @samples.each do |sample| %>
<% manid = Manid.find(sample.manid_id) %>
  <tr>
    <td><%= manid.customer %></td>
    <td><%= manid.can_id %></td>
    <td><%= sample.status %></td>
    <td><%= sample.dateExchange %></td>
    <td><%= sample.dateSamples %></td>
    <td><%= sample.dateCustApproval %></td>
    <td><%= sample.dateReleaseProduction %></td>
    <td><%= sample.target %></td>
    <td><%= sample.dateQAEnable %></td>
    <td><%= sample.crs %></td>
    <td><%= link_to 'Show', sample %></td>
    <td><%= link_to 'Edit', edit_sample_path(sample) %></td>
    <td><%= link_to 'Destroy', sample, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New Sample', new_sample_path %>

app/views/samples/new.html.erb
<h1>New sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Manid Record Number:</b>
  <%= @sample.manid_id %>
</p>

<p>
  <b>Status:</b>
  <%= @sample.status %>
</p>

<p>
  <b>Date Secret/Signature Exchange:</b>
  <%= @sample.dateExchange %>
</p>

<p>
  <b>Date Samples Shipped:</b>
  <%= @sample.dateSamples %>
</p>

<p>
  <b>Datecustapproval:</b>
  <%= @sample.dateCustApproval %>
</p>

<p>
  <b>Date Production Program Available:</b>
  <%= @sample.dateReleaseProduction %>
</p>

<p>
  <b>Date Production Program Available - Target:</b>
  <%= @sample.target %>
</p>
<p>
  <b>Date Production Program Released:</b>
  <%= @sample.dateQAEnable %>
</p>

<p>
  <b>CRS Number:</b>
  <%= @sample.crs %>
</p>


<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>