config/routes.rb
TMS::Application.routes.draw do
  get "personalization/index"

  resources :task_logs

  get "sample_front/index"

  get "front_samples/index"

  get "task_front/top3Serial"

  get "task_front/top3All"

  get "task_front/taskonetwo"
  
  get "users/roster"

  resources :samples

  resources :manids

  resources :test_times

  get "sas_front/index"

  get "sas_front/reports"

  get "sas_front/deleteSa"

  resources :sas

  resources :targets

  resources :setups

  get "sas/index"

  resources :test_progs

  get "import_resource/import"

  get "import/npi"

  get "cost/import"

  resources :costings

  resources :projects

  resources :can_subs

  resources :can_mains

  resources :resources

  
  get "resource/index"
  
  get "resource/key_projects"

  get "admin/login"

  get "admin/logout"

  get "admin/index"

  get "main/test"

  resources :tasks

  resources :devices

  resources :users

  get "main/index"

  resources :ptos
  
  resources :sas_front do
    member do
      get 'mail'
    end
  end

  resources :tasks do
    member do
      get 'duplicate'
    end
  end

  match ':controller(/:action(/:id(.:format)))'
  
  resources :priority do
    collection do
      post 'reorder'
    end
  end
end

app/models/target.rb
class Target < ActiveRecord::Base
  before_save :programs_uppercase
  after_save :update_setup_match_cases

  def self.defaults( family )
    t = self.where("family in (?) AND device = 'default'", family).limit(1)
  end
  def self.device( family )
    t = self.where("family in (?) AND device != '' and tab = 'all'", family)
  end
  def self.device_tab( family )
    t = self.where("family in (?) AND tab != 'all'", family)
  end
  def self.wildcard( family )
    t = self.where("family in (?) AND '_' IN tab", family)
  end
  def self.sorted
    t = self.order("family, device, tab")
  end

  def cp1_tests
    [self.mag_cp1, self.mav_cp1, self.mag_x64_cp1]
  end

  def cp2_tests
    [self.mag_cp2, self.mav_cp2, self.mag_x64_cp2]
  end

  def cp3_tests
    [self.mag_cp3, self.mav_cp3, self.mag_x64_cp3]
  end

  def update_setup_match_cases
    setup = Setup.find_all_by_family(self.family)
    setup.each {|s|
      s.update_attribute(:updated_at,Time.now)
    }
  end

  private
  def programs_uppercase
    #self.family.upcase!
    self.device.upcase!
    self.mav_cp1.upcase!
    self.mav_cp2.upcase!
    self.mav_cp3.upcase!
    self.mag_cp1.upcase!
    self.mag_cp2.upcase!
    self.mag_cp3.upcase!
    self.mag_x64_cp1.upcase!
    self.mag_x64_cp2.upcase!
    self.mag_x64_cp3.upcase!
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  # GET /targets
  # GET /targets.xml
  def index
    @targets = Target.sorted

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @targets }
    end
  end

  # GET /targets/1
  # GET /targets/1.xml
  def show
    @target = Target.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @target }
    end
  end

  # GET /targets/new
  # GET /targets/new.xml
  def new
    @target = Target.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @target }
    end
  end

  # GET /targets/1/edit
  def edit
    @target = Target.find(params[:id])
  end

  # POST /targets
  # POST /targets.xml
  def create
    @target = Target.new(params[:target])

    respond_to do |format|
      if @target.save
        format.html { redirect_to(@target, :notice => 'Target was successfully created.') }
        format.xml  { render :xml => @target, :status => :created, :location => @target }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @target.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /targets/1
  # PUT /targets/1.xml
  def update
    @target = Target.find(params[:id])

    respond_to do |format|
      if @target.update_attributes(params[:target])
        format.html { redirect_to(@target, :notice => 'Target was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @target.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.xml
  def destroy
    @target = Target.find(params[:id])
    @target.destroy

    respond_to do |format|
      format.html { redirect_to(targets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.erb
<%= form_for(@target) do |f| %>
  <% if @target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@target.errors.count, "error") %> prohibited this target from being saved:</h2>

      <ul>
      <% @target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :family %><br />
    <%= f.text_field :family %>
  </div>
  <div class="field">
    <%= f.label :device %><br />
    <%= f.text_field :device %>
  </div>
  <div class="field">
    <%= f.label :tab %><br />
    <%= f.text_field :tab %>
  </div>
  <div class="field">
    <%= f.label :mag_cp1 %><br />
    <%= f.text_field :mag_cp1 %>
  </div>
  <div class="field">
    <%= f.label :mag_cp2 %><br />
    <%= f.text_field :mag_cp2 %>
  </div>
  <div class="field">
    <%= f.label :mag_cp3 %><br />
    <%= f.text_field :mag_cp3 %>
  </div>
  <div class="field">
    <%= f.label :mag_x64_cp1 %><br />
    <%= f.text_field :mag_x64_cp1 %>
  </div>
  <div class="field">
    <%= f.label :mag_x64_cp2 %><br />
    <%= f.text_field :mag_x64_cp2 %>
  </div>
  <div class="field">
    <%= f.label :mag_x64_cp3 %><br />
    <%= f.text_field :mag_x64_cp3 %>
  </div>
  <div class="field">
    <%= f.label :mav_cp1 %><br />
    <%= f.text_field :mav_cp1 %>
  </div>
  <div class="field">
    <%= f.label :mav_cp2 %><br />
    <%= f.text_field :mav_cp2 %>
  </div>
  <div class="field">
    <%= f.label :mav_cp3 %><br />
    <%= f.text_field :mav_cp3 %>
  </div>
  <div class="field">
    <%= f.label :cr3 %><br />
    <%= f.check_box :cr3 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/targets/edit.html.erb
<h1>Editing target</h1>

<%= render 'form' %>

<%= link_to 'Show', @target %> |
<%= link_to 'Back', targets_path %>

app/views/targets/index.html.erb
<h1>Listing targets</h1>
<div class="btn-group">
  <a class="btn btn-primary" href="/setup_sync/prr?family=2Wire">2 Wire</a>
  <a class="btn btn-primary" href="/setup_sync/prr?family=3Wire">3 Wire</a>
  <a class="btn btn-primary" href="/setup_sync/prr?family=SPI">SPI</a>
  <a class="btn btn-primary" href="/setup_sync/prr?family=Crypto">Crypto</a>
  <a class="btn btn-primary" href="/setup_sync/prr?family=TS">Temp Sensor</a>
</div>
<div class="btn-group">
  <a class="btn btn-primary" href="/setup_sync/prr?family=AVR8">AVR8</a>
  <a class="btn btn-primary" href="/setup_sync/prr?family=AVR32">AVR32</a>
  <a class="btn btn-primary" href="/setup_sync/prr?family=ARM">ARM</a>
  <a class="btn btn-primary" href="/setup_sync/prr?family=C51">C51</a>
  <a class="btn btn-primary" href="/setup_sync/prr?family=XMEGA">XMEGA</a>
  <a class="btn btn-primary" href="/setup_sync/prr?family=Touch">Touch</a>
</div>
<div class="btn-group">
  <a class="btn btn-primary" href="/targets">Target</a>
</div>
<div class="btn-group">
  <a class="btn btn-primary" href="/setup_sync/report?report=EPRO">EPRO Entries</a>
  <a class="btn btn-primary" href="/setup_sync/report?report=RED">RED Report</a>
  <a class="btn btn-primary" href="/setup_sync/report?report=x_flow">X-Flows</a>
</div>
<table cellspacing="10" class="display compact" id="prr" width="100%">
  <thead>
    <tr>
      <th>Family</th>
      <th>Device</th>
      <th>Tab</th>
      <th>Mag cp1</th>
      <th>Mag cp2</th>
      <th>Mag cp3</th>
      <th>Mag x64 cp1</th>
      <th>Mag x64 cp2</th>
      <th>Mag x64 cp3</th>
      <th>Mav cp1</th>
      <th>Mav cp2</th>
      <th>Mav cp3</th>
      <th>CR3 approved</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @targets.each do |target| %>
      <tr>
        <td>
          <%= target.family %>
        </td>
        <td>
          <%= target.device %>
        </td>
        <td>
          <%= target.tab %>
        </td>
        <td>
          <%= target.mag_cp1 %>
        </td>
        <td>
          <%= target.mag_cp2 %>
        </td>
        <td>
          <%= target.mag_cp3 %>
        </td>
        <td>
          <%= target.mag_x64_cp1 %>
        </td>
        <td>
          <%= target.mag_x64_cp2 %>
        </td>
        <td>
          <%= target.mag_x64_cp3 %>
        </td>
        <td>
          <%= target.mav_cp1 %>
        </td>
        <td>
          <%= target.mav_cp2 %>
        </td>
        <td>
          <%= target.mav_cp3 %>
        </td>
        <td>
          <%= raw checkbox(target.cr3) %>
          <i class="icon-search"></i>
        </td>
        <td>
          <%= link_to 'Show', target,:class =>'btn btn-info' %>
        </td>
        <td>
          <%= link_to raw('<span class="glyphicon glyphicon-edit"></span>'), edit_target_path(target) %>
        </td>
        <td>
          <%= link_to raw('<span class="glyphicon glyphicon-remove"></span>'), target, :confirm => 'Are you sure?', :method => :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<%= link_to 'New Target', new_target_path, :class =>'btn btn-primary' %>

app/views/targets/new.html.erb
<h1>New target</h1>

<%= render 'form' %>

<%= link_to 'Back', targets_path %>

app/views/targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Family:</b>
  <%= @target.family %>
</p>

<p>
  <b>Device:</b>
  <%= @target.device %>
</p>

<p>
  <b>Tab:</b>
  <%= @target.tab %>
</p>

<p>
  <b>Mag cp1:</b>
  <%= @target.mag_cp1 %>
</p>

<p>
  <b>Mag cp2:</b>
  <%= @target.mag_cp2 %>
</p>

<p>
  <b>Mag x64 cp1:</b>
  <%= @target.mag_x64_cp1 %>
</p>

<p>
  <b>Mag x64 cp2:</b>
  <%= @target.mag_x64_cp2 %>
</p>

<p>
  <b>Mav cp1:</b>
  <%= @target.mav_cp1 %>
</p>

<p>
  <b>Mav cp2:</b>
  <%= @target.mav_cp2 %>
</p>

<p>
  <b>CR3:</b>
  <%= @target.cr3 %>
</p>


<%= link_to 'Edit', edit_target_path(@target) %> |
<%= link_to 'Back', targets_path %>