config/routes.rb
TMS::Application.routes.draw do
  get "personalization/index"

  resources :task_logs

  get "sample_front/index"

  get "front_samples/index"

  get "task_front/top3Serial"

  get "task_front/top3All"

  get "task_front/taskonetwo"
  
  get "users/roster"

  resources :samples

  resources :manids

  resources :test_times

  get "sas_front/index"

  get "sas_front/reports"

  get "sas_front/deleteSa"

  resources :sas

  resources :targets

  resources :setups

  get "sas/index"

  resources :test_progs

  get "import_resource/import"

  get "import/npi"

  get "cost/import"

  resources :costings

  resources :projects

  resources :can_subs

  resources :can_mains

  resources :resources

  
  get "resource/index"
  
  get "resource/key_projects"

  get "admin/login"

  get "admin/logout"

  get "admin/index"

  get "main/test"

  resources :tasks

  resources :devices

  resources :users

  get "main/index"

  resources :ptos
  
  resources :sas_front do
    member do
      get 'mail'
    end
  end

  resources :tasks do
    member do
      get 'duplicate'
    end
  end

  match ':controller(/:action(/:id(.:format)))'
  
  resources :priority do
    collection do
      post 'reorder'
    end
  end
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :project %><br />
    <%= f.text_field :project %>
  </div>
  <div class="field">
    <%= f.label :function %><br />
    <%= f.text_field :function %>
  </div>
  <div class="field">
    <%= f.label :actual %><br />
    <%= f.text_field :actual %>
  </div>
  <div class="field">
    <%= f.label :forecast %><br />
    <%= f.text_field :forecast %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table class="table">
  <tr>
    <th>Date</th>
    <th>Department</th>
    <th>Name</th>
    <th>Project</th>
    <th>Function</th>
    <th>Actual</th>
    <th>Forecast</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.date %></td>
    <td><%= resource.department %></td>
    <td><%= resource.name %></td>
    <td><%= resource.project %></td>
    <td><%= resource.function %></td>
    <td><%= resource.actual %></td>
    <td><%= resource.forecast %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @resource.date %>
</p>

<p>
  <b>Department:</b>
  <%= @resource.department %>
</p>

<p>
  <b>Name:</b>
  <%= @resource.name %>
</p>

<p>
  <b>Project:</b>
  <%= @resource.project %>
</p>

<p>
  <b>Function:</b>
  <%= @resource.function %>
</p>

<p>
  <b>Actual:</b>
  <%= @resource.actual %>
</p>

<p>
  <b>Forecast:</b>
  <%= @resource.forecast %>
</p>


<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>