config/routes.rb
TMS::Application.routes.draw do
  get "personalization/index"

  resources :task_logs

  get "sample_front/index"

  get "front_samples/index"

  get "task_front/top3Serial"

  get "task_front/top3All"

  get "task_front/taskonetwo"
  
  get "users/roster"

  resources :samples

  resources :manids

  resources :test_times

  get "sas_front/index"

  get "sas_front/reports"

  get "sas_front/deleteSa"

  resources :sas

  resources :targets

  resources :setups

  get "sas/index"

  resources :test_progs

  get "import_resource/import"

  get "import/npi"

  get "cost/import"

  resources :costings

  resources :projects

  resources :can_subs

  resources :can_mains

  resources :resources

  
  get "resource/index"
  
  get "resource/key_projects"

  get "admin/login"

  get "admin/logout"

  get "admin/index"

  get "main/test"

  resources :tasks

  resources :devices

  resources :users

  get "main/index"

  resources :ptos
  
  resources :sas_front do
    member do
      get 'mail'
    end
  end

  resources :tasks do
    member do
      get 'duplicate'
    end
  end

  match ':controller(/:action(/:id(.:format)))'
  
  resources :priority do
    collection do
      post 'reorder'
    end
  end
end

app/models/manid.rb
class Manid < ActiveRecord::Base
  belongs_to :sample
end

app/controllers/manids_controller.rb
class ManidsController < ApplicationController
  # GET /manids
  # GET /manids.xml
  def index
    @manids = Manid.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @manids }
    end
  end

  # GET /manids/1
  # GET /manids/1.xml
  def show
    @manid = Manid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @manid }
    end
  end

  # GET /manids/new
  # GET /manids/new.xml
  def new
    @manid = Manid.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @manid }
    end
  end

  # GET /manids/1/edit
  def edit
    @manid = Manid.find(params[:id])
  end

  # POST /manids
  # POST /manids.xml
  def create
    @manid = Manid.new(params[:manid])

    respond_to do |format|
      if @manid.save
        format.html { redirect_to(@manid, :notice => 'Manid was successfully created.') }
        format.xml  { render :xml => @manid, :status => :created, :location => @manid }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @manid.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /manids/1
  # PUT /manids/1.xml
  def update
    @manid = Manid.find(params[:id])

    respond_to do |format|
      if @manid.update_attributes(params[:manid])
        format.html { redirect_to(@manid, :notice => 'Manid was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @manid.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /manids/1
  # DELETE /manids/1.xml
  def destroy
    @manid = Manid.find(params[:id])
    @manid.destroy

    respond_to do |format|
      format.html { redirect_to(manids_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/manids_helper.rb
module ManidsHelper
end

app/views/manids/_form.html.erb
<%= form_for(@manid) do |f| %>
  <% if @manid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manid.errors.count, "error") %> prohibited this manid from being saved:</h2>

      <ul>
      <% @manid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device %><br />
    <%= f.text_field :device %>
  </div>
  <div class="field">
    <b>CPN</b><br />
    <%= f.text_field :cpn %>
  </div>
  <div class="field">
    <%= f.label :customer %><br />
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :products %><br />
    <%= f.text_field :products %>
  </div>
  <div class="field">
    <b>CAN</b><br />
    <%= f.text_field :can_id %>
  </div>
  <div class="field">
    <%= f.label :mfgid %><br />
    <%= f.text_field :mfgid %>
  </div>
  <div class="field">
    <%= f.label :protocol %><br />
    <%= f.text_field :protocol %>
  </div>
  <div class="field">
    <b>Sales POC</b><br />
    <%= f.text_field :pocmkt %>
  </div>
  <div class="field">
    <b>Applications POC</b><br />
    <%= f.text_field :pocapp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manids/edit.html.erb
<h1>Editing MANID Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @manid %> |
<%= link_to 'Back', manids_path %>

app/views/manids/index.html.erb
<h1>Listing Manufacturing IDs</h1>

<table cellspacing='10' class='display' id='prr' width='100%'>
    <thead>
  <tr>
    <th>Device</th>
    <th>CPN</th>
    <th>Customer</th>
    <th>Products</th>
    <th>Can</th>
    <th>Mfgid</th>
    <th>Protocol</th>
    <th>Sales POC</th>
    <th>Apps POC</th>
    <th></th>
    <th></th>
    <!-- <th></th> -->
  </tr>
</thead>
<tbody>
<% @manids.each do |manid| %>
  <tr>
    <td><%= manid.device %></td>
    <td><%= manid.cpn %></td>
    <td><%= manid.customer %></td>
    <td><%= manid.products %></td>
    <td><%= manid.can_id %></td>
    <td><%= manid.mfgid %></td>
    <td><%= manid.protocol %></td>
    <td><%= manid.pocmkt %></td>
    <td><%= manid.pocapp %></td>
    <td><%= link_to 'Create Qual Timeline', new_sample_path , :class => "btn btn-primary"%></td>
    <!-- <td><%= link_to 'Show', manid, :class => "btn btn-primary" %></td> -->
    <td><%= link_to 'Edit', edit_manid_path(manid), :class => "btn btn-warning" %></td>
    <!-- <td><%= link_to 'Destroy', manid, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-danger" %></td> -->
  </tr>
<% end %>
</tbody>
</table>
When creating a timeline record, please roll over the edit button of the record in question to get the manid record number from the URL bar.
<br />

<%= link_to 'New Manufacturing ID', new_manid_path , :class => "btn btn-primary"%>

app/views/manids/new.html.erb
<h1>New MANID Record</h1>

<%= render 'form' %>

<%= link_to 'Back', manids_path %>

app/views/manids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Device:</b>
  <%= @manid.device %>
</p>

<p>
  <b>Customer:</b>
  <%= @manid.customer %>
</p>

<p>
  <b>Products:</b>
  <%= @manid.products %>
</p>

<p>
  <b>Can:</b>
  <%= @manid.can_id %>
</p>

<p>
  <b>Mfgid:</b>
  <%= @manid.mfgid %>
</p>

<p>
  <b>Protocol:</b>
  <%= @manid.protocol %>
</p>

<p>
  <b>Sales POC</b>
  <%= @manid.pocmkt %>
</p>

<p>
  <b>Applications POC:</b>
  <%= @manid.pocapp %>
</p>
<%= link_to 'Edit', edit_manid_path(@manid) %> |
<%= link_to 'Back', manids_path %>